### ISSUE TITLE
array port index in FBP DSL

### ISSUE THREAD

**Issue by forresto** [flowbased/flow-based.org#21] opened 2014-09-20 08:21 UTC
How do I specify the array port index in FBP DSL? https://github.com/flowbased/flowbased.org/wiki/FBP-DSL

**Comment by oleksandr** [comment] 2014-09-20 08:52
@forresto AFAIK it's something like:
'iip' -> IN[0] Name(component) OUT[2] -> ...

**Comment by bergie** [comment] 2014-09-20 08:53
`Foo OUT[1] -> IN[5] Bar`.

Works already in the JavaScript FBP parser. See indices in action in noflo-ui graphs for instance

**Comment by oleksandr** [comment] 2014-09-20 08:54
@bergie Does it work also for INPORT/OUTPORT definitions?

**Comment by bergie** [comment] 2014-09-20 19:00
@oleksandr no. If you export an ArrayPort, it gets exported completely, not just a single index. You could export a single index by adding some no-op component in-between. Like this:

```
INPORT=Repeat.IN:IN
Repeat(core/Repeat) OUT -> IN[2] Too
```

But maybe adding index support would make sense to avoid this kind of unnecessary constructs

**Comment by oleksandr** [comment] 2014-09-20 20:58
I see. Exporting a separate index could be useful... I recall one sub-graph design where I placed a Splitter at the end of the flow and its OUT[0] was connected to an internal Logger, while the OUT[1] was intended to be exported. That was solved in another way but could be a nice solution indeed...

**Comment by jonnor** [comment] 2016-07-10 17:24
Question by original poster appears answered, so closing.
If exporting a dedicated index is still desired, suggest opening an issue in https://github.com/flowbased/fbp

**Closed as completed** 2016-07-10 17:24 UTC
Labels: question
